version: '3'

silent: true

tasks:

  build:
    desc: Builds debug target
    cmds:
      - cmd: ./scripts/build-debug.sh

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: ./scripts/clean.sh

  rebuild-clion:
    desc: Recreates build system for CLion
    cmds:
      - cmd: ./scripts/rebuild-clion.sh

  rebuild:
    desc: Recreates build system in target directory
    cmds:
      - cmd: ./scripts/rebuild-debug.sh
      - cmd: ./scripts/rebuild-release.sh

  release:
    desc: Builds release target
    cmds:
      - cmd: ./scripts/build-release.sh

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: ./scripts/test-debug.sh